### ISSUE TITLE
Writing CSS efficiently

### ISSUE THREAD

**Issue by jim-rosales** [achomiak/prj-rev-bwfs-dasmoto#3]
When writing CSS rules its best to analyzing how to efficiently apply the rules to avoid repeating yourself. For example to apply the blue color for all the prices you make use of ids like so:

```CSS
#pricebrushes {
  color:blue;
}

#priceframes {
  color:blue;
  font-weight: bold;
}

#pricepaint {
  color:blue;
  font-family: Helvetica;
  font-weight: bold;
}
```

Although those rules are valid its more efficient to apply the desired styles like so:

```CSS
strong {
  color: blue;
}
```

The reason that is equivalent to the rules you wrote is because the `strong` element applies the bold automatically, and the Helvetica font is inherited from the body rule you applied at the start of the stylesheet. 

https://github.com/achomiak/prj-rev-bwfs-dasmoto/blob/2ef8b426769afa6df8656a44f5fdf62f061429b4/Dasmoto/Resources/css/style.css#L59-L63
